server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html index.htm;

    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types 
        text/plain
        text/css
        text/javascript
        text/xml
        text/markdown
        application/javascript
        application/xml
        application/json;

    location /_astro/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp|avif|woff2|woff)$ {
        expires 30d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
